name: voice_message_package
description: Flutter package to play voice message in chats.
version: 0.0.74
homepage: https://github.com/mehranshoqi/voice_message_player

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^5.1.0
  just_audio: ^0.9.21
  syncfusion_flutter_sliders: ^23.1.36

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0


